[LightDM]
# Cho phép tạo nhiều seat
start-default-seat=true

[Seat:seat0]
# Seat mặc định cho màn hình 1
xserver-command=/usr/bin/X :0 -layout Layout0 -config /etc/X11/xorg.conf
user-session=ubuntu

[Seat:seat1]
# Seat thứ hai cho màn hình 2
xserver-command=/usr/bin/X :1 -layout Layout1 -config /etc/X11/xorg.conf
user-session=ubuntu
